### ISSUE TITLE
When sane testing is installed, nose is insane

### ISSUE THREAD

**Issue by honzakral** [Almad/django-sane-testing#1]
When I have sane testing installed and I run nosetests without it, I get a lot of warnings from sane testing.

**Comment by honzakral** [comment]
/home/king/work/VENVS/testing/lib/python2.7/site-packages/nose/plugins/manager.py:385: RuntimeWarning: Unable to load plugin cherrypyliveserver = djangosanetesting.noseplugins:CherryPyLiveServerPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
/home/king/work/VENVS/testing/lib/python2.7/site-packages/nose/plugins/manager.py:385: RuntimeWarning: Unable to load plugin sanetestselection = djangosanetesting.noseplugins:SaneTestSelectionPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
/home/king/work/VENVS/testing/lib/python2.7/site-packages/nose/plugins/manager.py:385: RuntimeWarning: Unable to load plugin djangoliveserver = djangosanetesting.noseplugins:DjangoLiveServerPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
/home/king/work/VENVS/testing/lib/python2.7/site-packages/nose/plugins/manager.py:385: RuntimeWarning: Unable to load plugin djangotranslations = djangosanetesting.noseplugins:DjangoTranslationPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
/home/king/work/VENVS/testing/lib/python2.7/site-packages/nose/plugins/manager.py:385: RuntimeWarning: Unable to load plugin selenium = djangosanetesting.noseplugins:SeleniumPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
/home/king/work/VENVS/testing/lib/python2.7/site-packages/nose/plugins/manager.py:385: RuntimeWarning: Unable to load plugin django = djangosanetesting.noseplugins:DjangoPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)

**Comment by Almad** [comment]
This actually happens only when there is an import of django project without proper settings of DJANGO_SETTINGS_MODULE/PYTHONPATH .

**Comment by Almad** [comment]
fixed.
