### ISSUE TITLE
It seems like selenium_patched_open() works wrong.

### ISSUE THREAD

**Issue by real-alexei** [Almad/django-sane-testing#10]
https://github.com/Almad/django-sane-testing/blob/master/djangosanetesting/utils.py#L175 looks unreachable and I think this line should replace line 168.

**Comment by yedpodtrzitko** [comment]
Original functionality will be achieved by deleting 'return' from line 168.

**Comment by Almad** [comment]
Thanks for catching this, this is what we get for defunct tests :) (is_text_present must be asserted...).

**Comment by Almad** [comment]
Refactor tests, expose nonworky selenium code. Closed by 58ad092d59357899958a9d6f801aff6f7925e3c3

**Comment by Almad** [comment]
(also, #3 reopened)
