### ISSUE TITLE
Test selection/detection (Django 1.3 + nose)

### ISSUE THREAD

**Issue by botondus** [Almad/django-sane-testing#42]
This is pretty strange but it seems like if I use any of the *TestCase (for example UnitTestCase and DatabaseTestCase) classes from djangosanetesting, the tests are simply not detected and run.

(***_)botondus@botondus-laptop:~/Envs/**_/$ python manage.py test -v 3
nosetests --verbosity 3
nosetests --verbosity 3 --with-django --with-selenium --with-djangotranslations --with-djangoliveserver
nose.selector: INFO: /home/botondus/Envs/***/manage.py is executable; skipped

---

Ran 0 tests in 0.001s

There should be 3 tests, if I set them to inherit from django's TestCase they are detected OK. 
I do have the DST testrunner set

TEST_RUNNER='djangosanetesting.testrunner.DstNoseTestSuiteRunner'

**Comment by Almad** [comment]
Could You please take a look at #38 and tell me whether it's not the same problem?

**Comment by botondus** [comment]
Hmm..indeed it does seem to be the same issue.

**Comment by Almad** [comment]
Thanks for verification.

Closing as duplicate, moving #38 higher on my todo ;)
