### ISSUE TITLE
More assert functions

### ISSUE THREAD

**Issue by honzakral** [Almad/django-sane-testing#9]
please consider mimicking nose in exposing all unittest assert functions as found in:

http://code.google.com/p/python-nose/source/browse/nose/tools.py?r=d249b8e58776d8d81541a87916faf48846beccaa#172

**Comment by Almad** [comment]
Scrape unittest(2) for assert functions. Closed by 3e45413b9078fff81cfe9f7a173f0a23c27fcc49
